### ISSUE TITLE
Version 2.2.1 not working on check_mk 1.5.0p13

### ISSUE THREAD

**Issue by sbeccato** [ImTheLucKyOne/check_mk_emcunity#18]
Hi,
just tried to work with version 2.2.1 of this check in Check_mk RAW 1.5.0p13 (emcunity-2.2.1.mkp) but is not working, I had to switch to the old version ( emcunity300-1.2.4.mkp )

**Comment by ImTheLucKyOne** [comment]
Try if the 2.2.0 package is working for you.
1.2.4 is not 100% functional with cmk 1.5.0.

Which issues did you have with the 2.2.1 package exactly?

**Comment by zahnrad97** [comment]
Hi,
version 1.5.p23 

var/log/web.log

2019-11-20 07:09:05,929 [40] [cmk.web 6504] /help/check_mk/side.py Internal error: Traceback (most recent call last):
  File "/omd/sites/help/share/check_mk/web/htdocs/index.py", line 67, in handler
    modules.load_all_plugins()
  File "/omd/sites/help/share/check_mk/web/htdocs/modules.py", line 127, in load_all_plugins
    module.load_plugins(force = need_plugins_reload)
  File "/omd/sites/help/share/check_mk/web/htdocs/metrics.py", line 93, in load_plugins
    load_web_plugins("metrics", globals())
  File "/omd/sites/help/share/check_mk/web/htdocs/lib.py", line 184, in load_web_plugins
    execfile(file_path, globalvars)
  File "/omd/sites/help/local/share/check_mk/web/plugins/metrics/emcunity.py", line 4, in <module>
    from cmk.gui.plugins.metrics.check_mk import df_translation
ImportError: No module named gui.plugins.metrics.check_mk

**Comment by ImTheLucKyOne** [comment]
Please download the updated 2.2.1 package again.

https://github.com/ImTheLucKyOne/check_mk_emcunity/blob/master/emcunity300/emcunity-2.2.1.mkp

I reverted the changes for cmk 1.6.0 in this package and created a new one 2.2.2 for cmk 1.6.0 compatibility.
