### ISSUE TITLE
Attempting to install 2.2.2 on cmk 1.6.0p12 results in failure

### ISSUE THREAD

**Issue by pdrangeid** [ImTheLucKyOne/check_mk_emcunity#20]
CentOS 7.8.2003 (Core)
When attempting to install the mkp I get the following error:

OMD[prod]:/opt/omd/versions/1.6.0p12.cre/bin$ mkp install /tmp/emcunity-2.2.2.mkp
Traceback (most recent call last):
  File "/omd/sites/prod/bin/check_mk", line 94, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/prod/lib/python/cmk_base/modes/__init__.py", line 72, in call
    return mode.handler_function(*handler_args)
  File "/omd/sites/prod/lib/python/cmk_base/modes/check_mk.py", line 626, in mode_packaging
    cmk_base.packaging.do_packaging(*args)
  File "/omd/sites/prod/lib/python/cmk_base/packaging.py", line 185, in do_packaging
    f(args)
  File "/omd/sites/prod/lib/python/cmk_base/packaging.py", line 524, in package_install
    return install_package(file_name=path)
  File "/omd/sites/prod/lib/python/cmk_base/packaging.py", line 528, in install_package
    tar = tarfile.open(name=file_name, fileobj=file_object, mode="r:gz")
  File "/omd/sites/prod/lib/python2.7/tarfile.py", line 1693, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/prod/lib/python2.7/tarfile.py", line 1751, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

**Comment by ImTheLucKyOne** [comment]
Sorry for the late response:

I created a new package in cmk 1.6.0p13.
Download the new package and install it with `cmk -P install emcunity-2.2.3.mmkp`.
